# name: Sync Branches

# on:
#   push:
#     branches:
#       - main

# jobs:
#   sync-branches:
#     runs-on: ubuntu-latest

#     steps:
#       - name: Checkout code
#         uses: actions/checkout@v3

#       - name: Checkout code
#         run: git fetch origin prod:prod

#       - name: Switch to prod
#         run: git checkout prod

#       - name: Set Git user identity
#         run: |
#           git config --local user.email "anandabhishek.78@hotmail.com"
#           git config --local user.name "anandabhishek1402"

#       - name: Preserve specific files
#         run: |
#           git checkout prod -- dbt_project.yml packages.yml

#       - name: Merge changes from main
#         run: git merge main --allow-unrelated-histories

#       - name: Push changes to prod
#         run: |
#           git config --local user.email "anandabhishek.78@hotmail.com"
#           git config --local user.name "anandabhishek1402"
#           git push origin prod
