name: Sync Main to Prod

on:
  push:
    branches:
      - main

jobs:
  sync-main-to-prod:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Checkout code fetch
        run: git fetch origin prod:prod

      - name: Create and switch to prod branch
        run: |
          git checkout prod
          
      - name: Set Git user identity
        run: |
          git config --local user.email "anandabhishek.78@hotmail.com"
          git config --local user.name "anandabhishek1402"

      - name: Merge changes from main
        run: |
          git fetch origin main
          git merge origin/main --no-commit --no-ff --allow-unrelated-histories
          git checkout -- dbt_project.yml  # Discard changes to dbt_project.yml
          git commit -am "Merge changes from main to prod"

      - name: Push changes to prod
        run: |
          git push origin prod
