
# name: Sync
# on:
#   push:
#     branches:
#       - main

# jobs:
#   createPullRequest:
#     runs-on: ubuntu-latest
#     steps:
#       - uses: actions/checkout@v4

#       - name: Make changes to pull request
#         run: date +%s > report.txt

#       - name: Create Pull Request
#         id: cpr
#         uses: peter-evans/create-pull-request@v6
#         with:
#           branch: prod
#           delete-branch: false
#           add-paths: |
#             models/*.sql

#       - name: Set Git user identity
#         run: |
#           git config --local user.email "anandabhishek.78@hotmail.com"
#           git config --local user.name "anandabhishek1402"

#       - name: Checkout Prod
#         run: |
#           git checkout prod
#           git reset HEAD dbt_project.yml .github/workflows/peter.yml
#           git status
#           git commit -m "Merge main into prod (excluding dbt_project.yml and .github/workflows/peter.yml)"
#           git push -u origin prod

