name: Sync Branches

on:
  push:
    branches:
      - main

jobs:
  sync-branches:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        
      - name: Set Git identity
        run: |
          git config user.email abhishekanan@mediabymother.com
          git config user.name abhishekanan-cyb

      - name: Skip specific files
        run: |
          git checkout HEAD -- dbt_project.yml packages.yml  # Discard changes to specific files
          git commit -m "Skip specific files during sync"

      - name: Push changes to synced-branch
        run: |
          git checkout prod
          git push origin prod
